# -*- coding: utf-8 -*-
"""Road Trip Cost Estimator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ny6WTZY5b4Ld433UQ9A3u6tQsaEK51Q
"""

def calculate_fuel_cost (distance, consumption, price, passengers):
    total_fuel = distance * consumption / 100
    fuel_cost = total_fuel * price
    fuel_per_person = fuel_cost / passengers
    return total_fuel, fuel_cost, fuel_per_person

def calculate_stay_cost (days, daily_budget):
    stay_cost = days * daily_budget
    return stay_cost

def print_report (departure, destination, total_distance, passengers, fuel_consumption, total_fuel, fuel_price, fuel_cost, fuel_per_person, trip_duration, daily_budget, stay_cost, total_per_person):
    print ("======= ROAD TRIP ESTIMATOR =======")
    print(f"{'Route:':<14} {departure} → {destination}")
    print(f"{'Distance:':<14} {total_distance:.0f} km")
    print(f"{'Passengers:':<14} {passengers}")
    print()
    print("---- Fuel ----")
    print(f"{'Consumption:':<14} {fuel_consumption:.1f} L/100km")
    print(f"{'Total Fuel:':<14} {total_fuel:.2f} L")
    print(f"{'Fuel Price:':<14} {fuel_price:.2f} EUR/L")
    print(f"{'Fuel Cost:':<14} {fuel_cost:.2f} EUR")
    print(f"{'Per Person:':<14} {fuel_per_person:.2f} EUR")
    print()
    print("---- Stay ----")
    print(f"{'Duration:':<14} {trip_duration} days")
    print(f"{'Daily Budget:':<14} {daily_budget:.2f} EUR/person")
    print(f"{'Stay Cost:':<14} {stay_cost:.2f} EUR/person")
    print()
    print("--- TOTAL PER PERSON ---")
    print(f"{'':<14} {total_per_person:.2f} EUR")
    print("=" * 36)

departure = input("What is departure city? ")
destination = input("What is destination city? ")
passengers = int(input("What is the number of passengers? "))
total_distance = float(input("What is total distance in km? "))
fuel_consumption = float(input("What is fuel consumption in L/100km? "))
fuel_price = float(input("What is fuel price per liter? "))
trip_duration = int(input("What is number of days on vacation? "))
daily_budget = float(input("What is daily budget per person? "))

total_fuel, fuel_cost, fuel_per_person = calculate_fuel_cost (total_distance, fuel_consumption, fuel_price, passengers)
stay_cost = calculate_stay_cost (trip_duration, daily_budget)
total_per_person = fuel_per_person + stay_cost
print_report (departure, destination, total_distance, passengers, fuel_consumption, total_fuel, fuel_price, fuel_cost, fuel_per_person, trip_duration, daily_budget, stay_cost, total_per_person)