# -*- coding: utf-8 -*-
"""Workout Session Logger

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sO6VZja2CHZGubekNZjvxhLxV0nUhCzR
"""

def calculate_volume( sets, reps, weight):
    volume = sets * reps * weight
    return volume

athlete = input("What is your name? ")
name1 = input("What is exercise name? ")
sets1 = int(input("What is number of sets? "))
reps1 = int(input("What is number of reps? "))
weight1 = float(input("What is weight? "))
name2 = input("What is exercise name? ")
sets2 = int(input("What is number of sets? "))
reps2 = int(input("What is number of reps? "))
weight2 = float(input("What is weight? "))
name3 = input("What is exercise name? ")
sets3 = int(input("What is number of sets? "))
reps3 = int(input("What is number of reps? "))
weight3 = float(input("What is weight? "))

print(f"==== WORKOUT SUMMARY - {athlete.upper()} ====")

def print_exercise (number, name, sets, reps, weight):
    volume = calculate_volume(sets, reps, weight)
    print (f"Exercise {number}: {name}")
    print (f"Sets: {sets} | Reps: {reps} | Weight: {weight} kg")
    print (f"Volume: {volume:,} kg")
    print ()
    return volume

volume1 = print_exercise (1, name1, sets1, reps1, weight1)
volume2 = print_exercise (2, name2, sets2, reps2, weight2)
volume3 = print_exercise (3, name3, sets3, reps3, weight3)

total_volume = volume1 + volume2 + volume3

def print_report (total_volume):
    print ("-" *36)
    print (f"Total Session Volume: {total_volume:,} kg")
    print ("-" *36)
    print("Great session! See you next time.")

print_report(total_volume)