# -*- coding: utf-8 -*-
"""Challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFJPMsEXEZg_jSWGygxlZ36RPOvnvOgL
"""

name = input ("What is your name? ")
print (f"Hello, {name}!")

width = int(input ("What is width of rectangle? "))
height = int(input ("What is height of rectangle? "))
print (f"Area: {width*height}")

fahrenheit = float(input ("What is the temperature in fahrenheit? "))
calculated_celsius = ((fahrenheit - 32) * 5 / 9)
print(f"{calculated_celsius:.2f}°C")

first = input ("What is your first name? ")
last = input ("What is your last name? ")
print (f"{last}, {first}")

bill = float(input("What is the amount of bill? "))
people = int(input("What is the number of people? "))
print(f"Each person pays: ${bill / people:.2f}")

first = input("What is your first name? ")
middle = input("What is your middle name? ")
last = input("What is your last name? ")
print(f"{first[0].upper()}.{middle[0].upper()}.{last[0].upper()}.")

bill = float(input("How much is the bill? "))
tip_percent = int(input("How much is the tip? "))
tip = tip_percent / 100 * bill
print(f"Tip: ${tip:.2f} \nTotal: ${bill + tip:.2f}")

def calculate_speed(distance, time):
    return distance/ time
distance = float(input("Enter distance (km): "))
time = float(input("Enter time (hours): "))

speed = calculate_speed(distance, time)
print(f"Average speed: {speed:.2f} km/h")

def speed_calculator(distance, time):
    return distance / time
distance = float(input("Enter distance (km): "))
time = float(input("Enter time (h): "))
speed = speed_calculator(distance, time)
print(f"Average speed: {speed:.3f} km/h")

name = input("What is the word? ")
print(f"{name.upper()}")
print(f"{name.capitalize()}")
print(f"{name[::-1]}")
print(f"{len(name)} characters")

def calculate_bmi(weight, height):
    return weight / height **2

weight = float(input("Enter your weight (kg): "))
height = float(input("Enter your height (m): "))
bmi_index = calculate_bmi(weight, height)
print(f"Your BMI is: {bmi_index:.1f}")