# -*- coding: utf-8 -*-
"""Personal Finance Snapshot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_z9lfbD6ZJFmZks82WxxBEHsRXT4Eh3f
"""

def savings_calculation(income, fixed_expenses, variable_expenses):
    total_expenses = fixed_expenses + variable_expenses
    net_savings = income - total_expenses
    savings_rate = (net_savings / income) * 100
    return total_expenses, net_savings, savings_rate
def get_status(savings_rate):
    if savings_rate <10:
       return "Warning: You are barely saving!"
    elif savings_rate <20:
       return "Decent. Room to improve."
    else:
       return "You are saving well! Keep it up!"
def print_report(income, fixed_expenses, variable_expenses, total_expenses, net_savings, savings_rate, status):
    print ("==== MONTHLY FINANCE SNAPSHOT ====")
    print (f"{'Monthly Income:':<20} {income:>10,.2f} EUR")
    print (f"{'Fixed Expenses:':<20} {fixed_expenses:>10,.2f} EUR")
    print (f"{'Variable Expenses:':<20} {variable_expenses:>10,.2f} EUR")
    print("-" * 36)
    print (f"{'Total Expenses:':<20} {total_expenses:>10,.2f} EUR")
    print (f"{'Total Savings:':<20} {net_savings:>10,.2f} EUR")
    print (f"{'Saving rate:':<20} {savings_rate:>10,.1f} %")
    print("-" * 36)
    print (f"Status: {status}")

income = float(input("What is your monthly income? "))
fixed_expenses = float(input("What is your monthly fixed expense? "))
variable_expenses = float(input("What is your monthly variable expense? "))

total_expenses, net_savings, savings_rate = savings_calculation (income, fixed_expenses, variable_expenses)
status = get_status(savings_rate)
print_report(income, fixed_expenses, variable_expenses, total_expenses, net_savings, savings_rate, status)